project:
  type: website

website:
  title: "Group_7"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: us.qmd
        text: Team
      - href: Introduction.qmd
        text: Introduction
      - href: index.qmd
        text: Code
      - href: References.qmd
        text: References
      
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

